# config/packages/menu.yaml
parameters:
    app_menu.sidebar:
        -
            title: Dashboard
            icon: 'bi bi-house-door-fill'
            route: app_dashboard
        -
            title: Configuraciones
            icon: 'bi bi-gear'
            roles: 'ROLE_ADMIN'
            children:
                -   title: Sistema
                    icon: 'bi bi-tools'
                    children: # <-- This triggers the recursion
                        - { title: Usuarios, route: app_user_index, icon: 'bi bi-person-lines-fill' }
                        - { title: Ciudades, route: app_ciudad_index, icon: 'bi bi-journal-check' }
                -   title: Alergias
                    icon: 'bi bi-virus'
                    children: # <-- This triggers the recursion
                        - { title: Alergenos, route: app_alergenos_index, icon: 'bi bi-virus2' }
                        - { title: Reacciones, route: app_reacciones_index, icon: 'bi bi-virus2' }
                - { title: Discapacidades, route: app_discapacidades_index }
                - { title: Tratamientos, route: app_tratamientos_index }
                - { title: Enfermedades, route: app_enfermedades_index }
                - { title: Medicamentos, route: app_medicamentos_index }
        -
            title: Pacientes
            icon: 'bi bi-people'
            roles: 'ROLE_INTERNAL'
            children:
                - { title: Pacientes Registrados, route: app_paciente_index, icon: 'bi bi-person-badge-fill' }
