# config/packages/menu.yaml
parameters:
    app_menu.sidebar:
        -
            title: Dashboard
            icon: 'bi bi-house-door-fill text-primary'
            route: app_dashboard
        -
            title: Configuraciones
            icon: 'bi bi-gear text-warning'
            roles: 'ROLE_ADMIN'
            children:
                -   title: Sistema
                    icon: 'bi bi-tools text-info'
                    children: # <-- This triggers the recursion
                        - { title: Usuarios Internos, route: app_user_internal_index, icon: 'bi bi-person-lines-fill text-info' }
                        - { title: Usuarios Externos, route: app_user_external_index, icon: 'bi bi-person-lines-fill text-info' }
                        - { title: Ciudades, route: app_ciudad_index, icon: 'bi bi-journal-check text-info' }
                -   title: Alergias
                    icon: 'bi bi-virus text-success'
                    children: # <-- This triggers the recursion
                        - { title: Alergenos, route: app_alergenos_index, icon: 'bi bi-virus2 text-success' }
                        - { title: Reacciones, route: app_reacciones_index, icon: 'bi bi-virus2 text-success' }
                - { title: Discapacidades, route: app_discapacidades_index, icon: 'bi bi-person-wheelchair text-warning' }
                - { title: Condiciones, route: app_condiciones_index, icon: 'fa-solid fa-person-cane text-warning' }
                - { title: Tratamientos, route: app_tratamientos_index, icon: 'fa-solid fa-syringe text-warning' }
                - { title: Enfermedades, route: app_enfermedades_index, icon: 'fa-solid fa-head-side-cough text-warning' }
                - { title: Medicamentos, route: app_medicamentos_index, icon: 'bi bi-capsule-pill text-warning' }
        -
            title: Pacientes
            icon: 'bi bi-people text-info'
            roles: 'ROLE_INTERNAL'
            children:
                - { title: Pacientes Registrados, route: app_paciente_index, icon: 'bi bi-person-badge-fill text-info' }
                - { title: Consultas, route: app_consulta_index, icon: 'bi bi-person-badge-fill text-info' }
